"use client";

import { useCallback, useEffect, useState } from "react";
import type { CommitDto, IssueDto, PaginatedDto, PullRequestDto, ReviewDto } from "@/lib/gitea/types";
import { CommitList, DataState, IssueList, PullRequestList, ReviewList, Section } from "./collaborator-ui";

type Result<T> = { data: T | null; error: string | null };
export default function RepositoryDetail({ owner, repository }: { owner: string; repository: string }) {
  const [state, setState] = useState({ loading: true, error: "" }); const [issues, setIssues] = useState<PaginatedDto<IssueDto> | null>(null); const [pulls, setPulls] = useState<PaginatedDto<PullRequestDto> | null>(null); const [commits, setCommits] = useState<PaginatedDto<CommitDto> | null>(null); const [reviews, setReviews] = useState<PaginatedDto<ReviewDto> | null>(null);
  const load = useCallback(async () => { const query = `owner=${encodeURIComponent(owner)}&repository=${encodeURIComponent(repository)}&page=1&limit=20`; const [issue, pull, commit] = await Promise.all([request<PaginatedDto<IssueDto>>(`/api/issues?${query}&type=issues`), request<PaginatedDto<PullRequestDto>>(`/api/pull-requests?${query}`), request<PaginatedDto<CommitDto>>(`/api/commits?${query}`)]); setIssues(issue.data ? { ...issue.data, items: issue.data.items.filter((item) => item.type === "issue") } : null); setPulls(pull.data); setCommits(commit.data); const reviewResults = await Promise.all((pull.data?.items ?? []).filter((item) => item.index !== null).map((item) => request<PaginatedDto<ReviewDto>>(`/api/reviews?${query}&index=${item.index}`))); setReviews({ items: reviewResults.flatMap((result) => result.data?.items ?? []), pagination: { page: 1, limit: 20, has_more: false } }); setState({ loading: false, error: issue.error || pull.error || commit.error || reviewResults.find((result) => result.error)?.error || "" }); }, [owner, repository]);
  useEffect(() => { void load(); }, [load]);
  if (state.loading) return <DataState kind="loading" />; if (state.error && !issues && !pulls && !commits) return <DataState kind="error" message={state.error} />;
  return <div className="mx-auto w-full max-w-7xl space-y-7"><header><p className="text-sm font-semibold uppercase tracking-[0.18em] text-sky-700">Repository</p><h1 className="mt-2 text-4xl font-semibold tracking-[-0.04em] text-slate-950">{owner}/{repository}</h1><p className="mt-3 text-slate-600">Données disponibles en lecture seule depuis Gitea.</p></header>{state.error && <DataState kind="error" message={state.error} />}<div className="grid gap-6 xl:grid-cols-2"><Section title="Issues">{issues?.items.length ? <IssueList data={issues} currentLogin={null} /> : <DataState kind="empty" message="Aucune issue retournée par Gitea." />}</Section><Section title="Pull requests">{pulls?.items.length ? <PullRequestList data={pulls} currentLogin={null} /> : <DataState kind="empty" message="Aucune pull request retournée par Gitea." />}</Section><Section title="Commits">{commits?.items.length ? <CommitList data={commits} currentLogin={null} /> : <DataState kind="empty" message="Aucun commit retourné par Gitea." />}</Section><Section title="Reviews">{reviews?.items.length ? <ReviewList data={reviews} /> : <DataState kind="empty" message="Aucune review disponible pour ce repository." />}</Section></div></div>;
}
async function request<T>(url: string): Promise<Result<T>> { try { const response = await fetch(url); const body = await response.json() as T | { error?: { message?: string } }; if (!response.ok) return { data: null, error: response.status === 403 || response.status === 404 ? "Cette capacité Gitea est indisponible pour ce repository." : `Accès indisponible (${response.status})` }; return { data: body as T, error: null }; } catch { return { data: null, error: "Impossible de joindre Gitea." }; } }
