"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";

type Repo = { full_name: string | null; name: string | null; html_url: string | null };
export default function Sidebar({ repositories, isAdmin }: { repositories: Repo[]; isAdmin: boolean }) {
  const pathname = usePathname();
  const [mobileOpen, setMobileOpen] = useState(false);
  const [repositoriesOpen, setRepositoriesOpen] = useState(true);
  const active = (href: string) => pathname === href || pathname.startsWith(`${href}/`);
  return <aside className="border-b border-slate-200 bg-white px-4 py-4 lg:min-h-screen lg:border-b-0 lg:border-r lg:px-5 lg:py-7"><div className="flex items-center justify-between"><Link className="text-xl font-bold tracking-tight text-slate-950" href="/collaborator"><span className="mr-2 inline-flex h-8 w-8 items-center justify-center rounded-xl bg-sky-600 text-sm text-white">D</span>DailyTrack</Link><button className="rounded-lg border border-slate-200 px-2 py-1 text-xs text-slate-600 lg:hidden" type="button" onClick={() => setMobileOpen((value) => !value)} aria-expanded={mobileOpen}>Menu</button></div><nav className={`${mobileOpen ? "mt-7" : "hidden lg:mt-7 lg:block"} space-y-1`} aria-label="Navigation principale"><Link className={`block rounded-xl px-3 py-2.5 text-sm font-medium ${active("/collaborator") ? "bg-sky-50 text-sky-800" : "text-slate-600 hover:bg-slate-50"}`} href="/collaborator">Dashboard</Link><div className="pt-5"><div className="flex items-center justify-between px-3"><span className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-400">Repositories</span><button type="button" onClick={() => setRepositoriesOpen((value) => !value)} className="text-lg leading-none text-slate-400" aria-label="Réduire la liste des repositories">{repositoriesOpen ? "−" : "+"}</button></div>{repositoriesOpen && <div className="mt-2 space-y-1">{repositories.length ? repositories.map((repo) => { const name = repo.full_name ?? repo.name; return name ? <Link key={name} className={`block truncate rounded-xl px-3 py-2 text-sm ${active(`/collaborator/repositories/${name}`) ? "bg-slate-100 font-semibold text-slate-900" : "text-slate-500 hover:bg-slate-50"}`} href={`/collaborator/repositories/${name}`}>{name}</Link> : null; }) : <p className="px-3 py-2 text-sm text-slate-400">Aucun repository accessible.</p>}</div>}</div><div className="mt-7 space-y-1 border-t border-slate-100 pt-5">{isAdmin && <Link className={`block rounded-xl px-3 py-2.5 text-sm font-medium ${active("/admin") ? "bg-sky-50 text-sky-800" : "text-slate-600 hover:bg-slate-50"}`} href="/admin">Admin</Link>}<Link className={`block rounded-xl px-3 py-2.5 text-sm font-medium ${active("/settings") ? "bg-sky-50 text-sky-800" : "text-slate-600 hover:bg-slate-50"}`} href="/settings">Paramètres</Link><a className="block rounded-xl px-3 py-2.5 text-sm text-slate-500 hover:bg-slate-50" href="/api/auth/gitea/logout">Déconnexion</a></div></nav></aside>;
}
